<?php
/**
 * @file
 * map_digital_heritage.features.field.inc
 */

/**
 * Implementation of hook_field_default_fields().
 */
function map_digital_heritage_field_default_fields() {
  $fields = array();

  // Exported field: 'node-digital_heritage-field_coverage'
  $fields['node-digital_heritage-field_coverage'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_coverage',
      'foreign keys' => array(),
      'indexes' => array(),
      'module' => 'geofield',
      'settings' => array(),
      'translatable' => '0',
      'type' => 'geofield',
    ),
    'field_instance' => array(
      'bundle' => 'digital_heritage',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Enter latitude and longitude values. <a href="http://www.getlatlon.com/">Look up</a> latitude and longitude values.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'geofield_map',
          'settings' => array(
            'geofield_map_baselayers_hybrid' => 1,
            'geofield_map_baselayers_map' => 1,
            'geofield_map_baselayers_physical' => 1,
            'geofield_map_baselayers_satellite' => 0,
            'geofield_map_controltype' => 'default',
            'geofield_map_draggable' => 1,
            'geofield_map_height' => '300px',
            'geofield_map_maptype' => 'hybrid',
            'geofield_map_mtc' => 'standard',
            'geofield_map_overview' => 0,
            'geofield_map_overview_opened' => 0,
            'geofield_map_pancontrol' => 1,
            'geofield_map_scale' => 1,
            'geofield_map_scrollwheel' => 0,
            'geofield_map_streetview_show' => 1,
            'geofield_map_width' => '100%',
            'geofield_map_zoom' => '5',
          ),
          'type' => 'geofield_map_map',
          'weight' => '17',
        ),
        'search_index' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'search_result' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_coverage',
      'label' => 'Coverage',
      'required' => 0,
      'settings' => array(
        'local_solr' => array(
          'enabled' => FALSE,
          'lat_field' => 'lat',
          'lng_field' => 'lng',
        ),
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'geofield',
        'settings' => array(),
        'type' => 'geofield_latlon',
        'weight' => '34',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Coverage');
  t('Enter latitude and longitude values. <a href="http://www.getlatlon.com/">Look up</a> latitude and longitude values.');

  return $fields;
}
